name: Flutter Build APK

on:
  push:
    branches:
      - main   # déclenche sur chaque push sur main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Flutter (version compatible avec Dart >= 3.8.0)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'

      # 3️⃣ Vérifier la version
      - name: Flutter version
        run: flutter --version

      # 4️⃣ Installer les dépendances
      - name: Install dependencies
        run: flutter pub get

     

      # 7️⃣ Construire l’APK en mode release
      - name: Build APK
        run: flutter build apk --release

      # 8️⃣ Sauvegarder l’APK comme artefact téléchargeable
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
